# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MxljXDfgv17X--vwBqMpt-aWnTjCcl9L
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import sklearn.preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from sklearn import svm

df = pd.read_csv('diabetes.csv')

df.isnull().sum()

df.head()

sns.heatmap(df.corr(),annot=True)

df.describe()

df.isnull().values.any()

zero_not_allowed = ["Glucose","BloodPressure","SkinThickness"]

for column in zero_not_allowed:
    df[column] = df[column].replace(0, np.NaN)
    mean = int(df[column].mean(skipna = True))
    df[column] = df[column].replace(np.NaN, mean)

X = df.drop('Outcome', axis=1).values
y = df['Outcome'].values

x_train, x_test, y_train, y_test = train_test_split(X, y, random_state = 0, test_size = 0.2)

model = svm.SVC(kernel='rbf')
model.fit(x_train,y_train)

y_pred = model.predict(x_test)
model.score(x_train,y_train)

print("Accuracy:", accuracy_score(y_test, y_pred))

